---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "{{ include "jaeger-operator-app.name" . }}-janitor"
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: linkerd-janitor
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  resourceNames:
  - jaegers.jaegertracing.io
  verbs:
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "jaeger-operator-app.name" . }}-janitor"
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "jaeger-operator-app.name" . }}-janitor"
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
subjects:
  - kind: ServiceAccount
    name: "{{ include "jaeger-operator-app.name" . }}-janitor"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ include "jaeger-operator-app.name" . }}-janitor"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "jaeger-operator-app.name" . }}-janitor"
  annotations:
    "helm.sh/hook": "post-delete"
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
  labels:
    app: linkerd-janitor
spec:
  template:
    spec:
      serviceAccountName: "{{ include "jaeger-operator-app.name" . }}-janitor"
      containers:
      - name: janitor
        image: "{{ .Values.kubectlImage.registry }}/{{ .Values.kubectlImage.name }}:{{ .Values.kubectlImage.tag }}"
        imagePullPolicy: "{{ .Values.kubectlImage.pullPolicy }}"
        command:
        - /bin/sh
        - -e
        - -c
        - >-
          kubectl delete crd jaegers.jaegertracing.io
      restartPolicy: Never
  backoffLimit: 6
