{{- if .Values.deployAllInOneInstance }}
apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: "{{ .Values.jaeger.instanceName }}"
spec:
  strategy: allInOne
  ingress:
    enabled: {{ .Values.jaeger.enableIngress }}
  allInOne:
    image: "{{ .Values.jaegerImage.registry }}/{{ .Values.jaegerImage.image }}:{{ .Values.jaegerImage.tag }}"
{{- if .Values.jaeger.enableDebug }}
    options:
      log-level: debug
{{- end }}
{{- end}}