checks:
  addAllBuiltIn: true
  exclude:
  - "dangling-service"
  - "no-liveness-probe"
  - "no-read-only-root-fs"
  - "no-readiness-probe"
  - "required-annotation-email"
  - "required-label-owner"
  - "run-as-non-root"
