# Default values for opencensus-collector-app.
# This is a YAML-formatted file.

replicaCount: 1

nameOverride: jaeger-operator
image:
  registry: ""
  image: jaegertracing/jaeger-operator
  tag: 1.17.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceType: ClusterIP

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

kubectlImage:
  registry: quay.io
  name: giantswarm/docker-kubectl
  tag: 933ac043b7bec33104aac58b16849ea28bace26c
  pullPolicy: IfNotPresent