# Default values for opencensus-collector-app.
# This is a YAML-formatted file.

nameOverride: jaeger-operator
fullnameOverride: ""

replicaCount: 1

image:
  registry: ""
  image: jaegertracing/jaeger-operator
  tag: 1.17.1
  pullPolicy: IfNotPresent

kubectlImage:
  registry: quay.io
  name: giantswarm/docker-kubectl
  tag: 933ac043b7bec33104aac58b16849ea28bace26c
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

# Warning: this setting allows to watch for CRDs in any namespace, but currently
# the cluster role has very wide permissions and poses a security risk!
# Don't enable until you really understand the consequences!
enableClusterScope: false