# Default values for jaeger-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  registry: quay.io
  repository: giantswarm/jaeger-operator
  tag: 1.41.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

global:
  podSecurityStandards:
    enforced: false

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

crd:
  install: true

jaeger:
  # Specifies whether Jaeger instance should be created
  create: true
  spec:
    strategy: allInOne
    ingress:
      enabled: true
    allInOne:
      image: quay.io/giantswarm/jaeger-all-in-one:1.51.0
    storage:
      type: memory
      options:
        memory:
          max-traces: 100000

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false
  clusterRole: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# exposes a service and corresponding service monitor for additional metrics via admin-http port 14269
collector:
  service:
    enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    interval: 10s
    scrapeTimeout: 10s
    scheme: http
    relabelings: []
    targetLabels: []
    metricRelabelings: []
    sampleLimit: 0

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}
